// <auto-generated />
using BlazorApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240116102023_ToInt")]
    partial class ToInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp.SharedLibrary.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Security System"
                        },
                        new
                        {
                            Id = 2,
                            Name = "High-Speed Internet Connectivity"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Energy-Efficient Lighting"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Flexible Workspace"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Smart HVAC Systems"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Customizable Interior Layouts"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Green Spaces"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Meeting Rooms with Tech Infrastructure"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Accessibility Features"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Waste Management Systems"
                        });
                });

            modelBuilder.Entity("BlazorApp.SharedLibrary.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Warsaw",
                            Country = "Poland"
                        },
                        new
                        {
                            Id = 2,
                            City = "Gdansk",
                            Country = "Poland"
                        });
                });

            modelBuilder.Entity("BlazorApp.SharedLibrary.Models.Premise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("RoomsCount")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Premises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Single room in unit (2+1) - from 430 EUR / month - 10-12 sqm - Fully furnished with a bed with storage space, comfortable mattress, desk and chair, wardrobe. Shared fridge in the hall with max. two persons - Shared bathroom with max. two persons. Nearby services: - Bus stop (160 meters) - Tram stop (350 meters) - Bars, restaurants and clubs - One of the greenest area in Warsaw. Feature check-list: - 24/7 reception support & security - High speed WiFi - Rooftop terrace, cinema room, shared kitchens, laundry room, study room, chill out zone - One card for everything - Front door, room door",
                            ImageUrl = "https://hotelverte.com/wp-content/uploads/2023/12/top-things-to-do-in-warsaw-old-town.jpg",
                            LocationId = 1,
                            Price = 3000000,
                            RoomsCount = 5,
                            Size = 129,
                            Street = "Pulawska",
                            Title = "Warsaw House"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tucked away at the edge of an ancient forest, this whimsical cottage seems plucked from the pages of a fairy tale. Its charming exterior, adorned with climbing ivy and surrounded by a vibrant garden, invites you into a world of enchantment. Inside, the warm glow of a fireplace dances on rustic wooden beams, creating a cozy atmosphere. Unique stained glass windows add a touch of magic to each room, casting colorful patterns that change with the shifting sunlight. The Enchanted Cottage is a haven for those seeking a retreat into a storybook setting.",
                            ImageUrl = "https://thumbor.forbes.com/thumbor/fit-in/900x510/https://www.forbes.com/home-improvement/wp-content/uploads/2022/07/download-23.jpg",
                            LocationId = 1,
                            Price = 4000000,
                            RoomsCount = 7,
                            Size = 180,
                            Street = "Zlota",
                            Title = "Warsaw Flat White"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Rising amidst the bustling cityscape, this sleek and stylish modern residence stands as a testament to contemporary design. The exterior's clean lines and large windows offer panoramic views of the surrounding urban jungle. Inside, an open-concept living space is adorned with minimalist furnishings, creating a sense of spaciousness. Smart home technology seamlessly integrates into every corner, allowing residents to control the ambiance with a touch. A rooftop terrace provides a private escape, offering a breathtaking skyline as a backdrop to the rhythmic pulse of the city below.",
                            ImageUrl = "https://mygate.com/wp-content/uploads/2023/07/110.jpg",
                            LocationId = 2,
                            Price = 250000,
                            RoomsCount = 10,
                            Size = 210,
                            Street = "Kazimierza Porebicza",
                            Title = "Gdansk Home"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Nestled on the shores of a tranquil lake, this rustic yet elegant house exudes a timeless charm. Weathered stone and cedar shingles blend seamlessly with the natural surroundings, while a sprawling porch offers a front-row seat to breathtaking sunsets. Inside, exposed wooden beams and a grand stone fireplace create a warm and inviting atmosphere. Large windows frame picturesque views of the lake, blurring the lines between indoor and outdoor living. A private dock extends into the water, inviting residents to embrace a serene lakeside lifestyle in this idyllic retreat.",
                            ImageUrl = "https://i.pinimg.com/736x/d0/c0/4b/d0c04be7f982a0753cb6dc0c565ea661.jpg",
                            LocationId = 1,
                            Price = 3450000,
                            RoomsCount = 3,
                            Size = 99,
                            Street = "Bulana Zlotego",
                            Title = "Flat in Warsaw center"
                        });
                });

            modelBuilder.Entity("BlazorApp.SharedLibrary.Models.PremiseFeature", b =>
                {
                    b.Property<int>("PremiseId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.HasKey("PremiseId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("PremiseFeatures");

                    b.HasData(
                        new
                        {
                            PremiseId = 1,
                            FeatureId = 6
                        },
                        new
                        {
                            PremiseId = 1,
                            FeatureId = 3
                        },
                        new
                        {
                            PremiseId = 1,
                            FeatureId = 4
                        },
                        new
                        {
                            PremiseId = 2,
                            FeatureId = 1
                        },
                        new
                        {
                            PremiseId = 2,
                            FeatureId = 7
                        },
                        new
                        {
                            PremiseId = 2,
                            FeatureId = 2
                        },
                        new
                        {
                            PremiseId = 3,
                            FeatureId = 10
                        },
                        new
                        {
                            PremiseId = 3,
                            FeatureId = 4
                        },
                        new
                        {
                            PremiseId = 3,
                            FeatureId = 9
                        },
                        new
                        {
                            PremiseId = 4,
                            FeatureId = 3
                        },
                        new
                        {
                            PremiseId = 4,
                            FeatureId = 6
                        },
                        new
                        {
                            PremiseId = 4,
                            FeatureId = 8
                        });
                });

            modelBuilder.Entity("BlazorApp.SharedLibrary.Models.Premise", b =>
                {
                    b.HasOne("BlazorApp.SharedLibrary.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("BlazorApp.SharedLibrary.Models.PremiseFeature", b =>
                {
                    b.HasOne("BlazorApp.SharedLibrary.Models.Feature", "Feature")
                        .WithMany("PremiseFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp.SharedLibrary.Models.Premise", "Premise")
                        .WithMany("PremiseFeatures")
                        .HasForeignKey("PremiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Premise");
                });

            modelBuilder.Entity("BlazorApp.SharedLibrary.Models.Feature", b =>
                {
                    b.Navigation("PremiseFeatures");
                });

            modelBuilder.Entity("BlazorApp.SharedLibrary.Models.Premise", b =>
                {
                    b.Navigation("PremiseFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
